DedicatedServer/Scripts/Libs/Zrx/ModeLibs/Common/WarmUpReadyUp/WarmUpReadyUp.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_Common.Script.txt

Issue #68
Not sure how this Null Player can even happen. Only saw the Ingame traceback that reaby sent. Afaik, that issue didn't happen since then.
In extreme edge cases it might be, that a ready state change of a player will not be registered by the server, if the Player is Null. Then the player would have to unready and ready again. But that should be an edge case and shouldn't happen (at all actually).

Added a null check for player when pressing ready button

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/Common/EventFeed.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_TimeWarnings.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Header.Script.txt
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

See issue #69.
- Messages and event feeds broadcasted at 60 and 30 seconds remaining (unless round timelimit setting <= 60). Same thing for warmup 5 seconds before starting (only event feed message).
- Red timer when below 30 seconds. Couldn't make the timer blinking due to limited updates on the scoreboard (even when disabled, it didn't look too great).

Add Time Warnings

---

DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt
README.md

It's the issue iwth always resetting respawn timers that we already had. I thought we fixed it, but apparently we didn't.
This should do the trick though.
Important bugfix. Affected maps are for example spike valley and Terraformer. I can't think of other maps who have offzone or moving blocks right now.

Fix: Always resetting respawn timer when eliminated by offzone or squished by moving blocks

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/Common/WarmUpReadyUp/WarmUpReadyUp.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/Common/WarmUpReadyUp/WarmUpReadyUp_UI.Script.txt

Many players use Select/Menu für another action, like the ingame menu or scoreboard. R3 should have way less keybind clashes.

Warm up ready up pad shortcut changed from select to R3

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Menu.Script.txt

Here's a patch you were looking up for 👀
When testing a flagrush map in local mode (with the gamemode), exiting back to the editor is not possible because it can't actually quit the server. this should fix that behaviour. (untested on servers, but they should not be affected)

Fix exit button in local test

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_UI.Script.txt
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

From a suggestion on the discord. The change is to remove the "own", "opp" and "flg" trigrams to let players use their own. There was little feedback over this suggestion, and considering it didn't gather much attention, I concluded that the current trigrams were not much in use, so we'd rather let the player ones exist instead.

Remove trigrams

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_UI.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Markers.Script.txt
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

We've been reinitializing layers quite often, for example for the radar or markers. I changed it to update the layer manialinks instead, using the Update function from the library.
Also we don't need to init the whole UI at every map init and destroy it at every map end. Instead init once on ServerStart and Destroy on ServerEnd.
I changed the handling of how the flag spawn markers. There are now functions to explicitly hide the flag spawn markers and and the main flag marker. All markers (Bases, Flag spawns, Flag) are initialized once at the InitMap.

Update Layer handling (updates instead of re-inits)

---

DedicatedServer/Scripts/Libs/Rx/ModeLibs/Common/Hitbox.Script.txt
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

Use new UpDirection instead of Upwardness, decomposed Sideness into pitch and roll components to create a more accurate ellipsoid when the car is rolling left or right.

HitboxLib with latest API features.

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_Common.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_RpcEvents.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_UI.Script.txt
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

Issue: When a player scores a flag, the counter for the flags scored in the current round (small `+`-number) was not updated until anything else in the players score changed again.
Probably due to a small mistake during refactoring where I moved the wrong lines to the wrong spots. (Player score update in section commented with `// Team` and also the other way around)
Also fixed a typo in the name of the Telemetry key constant.

fix player flags scored sync

---

CHANGELOG.md
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Menu.Script.txt

- Added a callvotes page
- Added a color to the quit confirmation as some players seemed confused in the beginning why the quit button wasn't working
- Join team buttons had a static defined color as the focusarea color cannot be changed via script (thanks for nothing, Nadeo). Now using the team color for the button frame instead. (Still hoping that in the future changing team colors will be viable.
Menu should generally still work the same as before. Please try it out and point out issues.
Closes #191

Pause menu refactoring; Add callvotes page

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/Common/WarmUpReadyUp/WarmUpReadyUp.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_UI.Script.txt

Replaced the Layers lib from the Legacy folder with the current version... which is practically the same, except for 2 new methods (GetScriptName & GetScriptVersion) and formatting.
Necessary? Probably not. But just keep it updated, I guess.

Replace legacy Layers lib with current lib

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Markers.Script.txt

Changes the icons of team bases / goals / finishes to shield icons for defense and crosshair icons for attack.
As player or while spectating a player:
As spectator in free cam:

Change base marker icons to shield and crosshair icons

---

GameClient/Scripts/MapTypes/FlagRushArena.Script.txt

- Reworks the logic behind anchor editing:
- Using layers instead of CMapEditorPlugin::ManialinkPage
- Layers directly write the anchor data
- Adds ability to select colors (hues) for teams
- Colors not(!) validated for hue overlap
- Hues saved in metadata as `FlagRush_Meta_TeamHues` of type `Real[Integer]` where array key is Clan number
- Hues in range [0.0; 1.0) or -1.0 to represent that the default colors should be used.

Maptype rework + Team color selection

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/BaseModes/FlagRushProgressionBase.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/Common/WarmUpReadyUp/WarmUpReadyUp.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/FlagRush_Messages.Script.txt

- Adds a setting (hidden) to determine if admin approval is needed to end warmup
- Timers in warmup will be aborted or not even started if no approval is given
- Mode command (through nadeo command interface and mode commands) to send approval

Add setting and commands for admin approval to end warmup (default off)

---

CHANGELOG.md
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Respawn.Script.txt
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

The respawn delay was always the same value for both teams, regardless of team sizes. This made it unfair for unbalanced teams in casual play and annoying with low amounts of player.
Instead, th respawn delay should now be dependent on teamsizes. Therefore a team with less players is less punished by respawning than a team with many players, making it easier to defend for the team that already in in a disadvantage.
Respawn delay is determined as follow: `S_RespawnDelayPerPlayer * ClansNbPlayers[Player.RequestedClan] * 1000`

Make respawn delay dependent on team size

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/FlagRush_Messages.Script.txt

Fix double prefix on chat messages send by FlagRush_Messages Lib

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/BaseModes/FlagRushProgressionBase.Script.txt

The podium is showing after map load, because the mode waits for player sync before changing the UI sequence, meaning that the Podium sequence is still active. Players that load before other will therefore see the podium for a short duration at the beginning of the new map.
Fixed by setting the UI sequence before performing the sync.

fix podium showing after map load

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Markers.Script.txt

Add a `#1` on the default flag spawn to indicate it as default flag spawn.
Also refactored the Manialink, as it got confusing while working on it. Not really logic changes, mainly just restructuring.

Add an indicator for the default flagspawn in warmup

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/FlagRush_UI.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/PodiumBackground.Script.txt

Due to network latency and the content of the podium background only being set during Manialink initialization it was possible for the podium screen to show the wrong content if manialink reached the client before the netvars.

Fix wrong scores being shown on podium

---

CHANGELOG.md
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_FlagState.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/FlagRush_UIShared.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Markers.Script.txt
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

In order to nerf flag relays, the following changes have been made:
- Manually dropping the flag in a stack of players is no longer considered a drop, but instead a pass/steal.
- No more flag steal resistance on passes between team members
- Picking up a dropped flag or stealing it from your opponent still gives steal resistance.
- Steal resistance can still be triggered by dropping the flag in front of your teammate who will pick it up at least 1 server frame later.
- A setting has been added to switch this behaviour (`S_FlagStealResistanceOnTeamPass`)

Flag relay nerf

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/FlagRush_Messages.Script.txt

After today's update, EUISound::Default does not play any sound anymore. ::PhaseChange is the same as the what ::Default was before.

Replace removed message sounds after march update

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Markers.Script.txt

fixes #250.
No marker is created for the flag-marker container during warmup, as a result it is displayed in the middle of the screen until its state is updated by a phase change. Hiding it by default should fix the issue

Hide flag marker during warmup

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/FlagRush_UI.Script.txt

Removes some CUIConfig parameters that are removed from the API in an upcoming update.
Waiting for that update to confirm that changes work as instended and script still compiles.

Remove deprecated CUIConfig properties

---

CHANGELOG.md
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

Closes #248 
When a player leaves the server in the same server frame as triggering a checkpoint or requesting a respawn, then the according events will report the player as Null. This can cause script crashes due to NPEs. Therefore, the events are checked for Null now.

Null-check player on waypoint events

---

CHANGELOG.md
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/FlagMarker.Script.txt

- Makes flag marker _practically_ bottom aligned, for better visibility when on player
- Adds fake pseudo 3D shadow below the flag icon when in dropped state

Fix flag marker car overlap

---

DedicatedServer/Scripts/Modes/TrackMania/FlagRush.Script.txt

We added this check in the past to the out of bounds triggers in the playloop, but didn't do so in the warmup. 🫠
Closes #281

Check player spawn status for out of bounds triggers in warmup

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_Map.Script.txt
DedicatedServer/Scripts/Modes/TrackMania/FlagRush.Script.txt

Adds a condition to not pass the flag to a team member if the carrier is trying to score the flag in the same yield.
Closes #282

Check if player is trying to score before passing the flag

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/BaseModes/FlagRushProgressionBase.Script.txt
DedicatedServer/Scripts/Modes/TrackMania/FlagRush.Script.txt
Mode settings.md

Remove unused settings `S_UseTurns` to reduce complexity.
This setting was added in the beginning when the future of the mode was unclear, but it was practically never used, as it doesn't fit into how the mode is played:
- Ending a turn after flag is scored brakes the flow and the dynamic of the round.
- The first flag of every round/turn is highly susceptible to "ping diff".

Remove setting S_UseTurns

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/FlagRush_UI.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/MapMarkers.Script.txt
DedicatedServer/Scripts/Modes/TrackMania/FlagRush.Script.txt
Mode settings.md

Remove unused settings S_UseReversedBases to reduce complexity.
This setting was added in the beginning when the future of the mode was unclear, but it was practically never used, as it doesn't fit into how the mode is played:
- Attacking your own base is too easy, as the defending side has no way of getting there quickly
- This is especially problematic if a defender crashes

Remove setting S_UseReversedBases

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/Flag.Script.txt
DedicatedServer/Scripts/Modes/TrackMania/FlagRush.Script.txt
Mode settings.md

Remove unused settings S_FlagInitialSpawnDelaySeconds and S_FlagRespawnDelaySeconds to reduce complexity.
These settings were added in the beginning when the future of the mode was unclear, but it was practically never used, as it doesn't fit into how the mode is played:
- Setting locks on flag when they spawn at landmark causes players to set up next to them, causing either "ping diff" issues or a random player to get the flag when multiple players cross the spawn in the same yield as the lock ends.
- Having players wait for the flag lock to expire breaks the flow and dynamics of a round.

Remove settings flag spawn delays

---

DedicatedServer/Scripts/Modes/TrackMania/FlagRush.Script.txt
Mode settings.md

Remove unused settings S_RandomizeFlagSpawns to reduce complexity.
This settings was added in the beginning when the future of the mode was unclear, but it was practically never used, as it doesn't fit into how the mode is played:
- Without random flag spawns, only the default flag spawn is used. All other flag spawns become unusable.
- Flag spawning becomes to predictable and camping flag spawns (after giving up defense or attack) becomes too easy.

Remove setting randomize flag spawns

---

CHANGELOG.md
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_Map.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_Vehicle.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/FlagMarker.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/FlagPossessionIndicator.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/VehicleSelection.Script.txt
DedicatedServer/Scripts/Modes/TrackMania/FlagRush.Script.txt
GameClient/Scripts/MapTypes/FlagRushArena.Script.txt
Mode settings.md

Closes #301 
Preparation for the Desert car Update.
- Adds the Desert car to the list in FlagRush_Vehicles
- Moves the display name and icon from Vehicle_Selection to FlagRush_Vehicles to have all vehicle properties in a central place
- Adds a new box for the flag marker when on a desert car
- Adds desert car tuning settings
- Adds the desert car to the FlagRush configuration dialog in the editor
- Also changes some unrelated `for`s to `foreach` that I introduced when adding support for the other cars
Todo:

Add Desert Vehicle
