DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

Fix match evaluation

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Header.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/ScoresTable.Script.txt

Added a 100ms update delay for scorestable and header

---

DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

Add timeout message and sfx

---

DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

Prioritize opponent on flag steals if multiple players overlap with flag carrier

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_UI.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Markers.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/RadarV2.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/UIShared.Script.txt
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

Radar flag height indicator

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Markers.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/RadarV2.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/UIShared.Script.txt
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

Use settingf or crude extrapolation

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_FlagState.Script.txt
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

Flag now drops on last safe position when player dies (0 Armor or PlayerResetTrigger

Flag now drops on last safe position when player dies

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Spectator.Script.txt

Spectator camera follows all player instead of all map if no carrier

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Radar.Script.txt

Sadly I couldn't actually do what I initially wanted to do. So this has really just some very minor optimizations. I almost saved nothing. :(

Radar optimization

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Radar.Script.txt

Fix self marker still displayed when carrying flag

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/Common/EventFeed.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Header.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Markers.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Radar.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/ScoresTable.Script.txt
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt
GameClient/Scripts/MapTypes/FlagRushArena.Script.txt

New quad style for the flag so it's not a triangle on a stick anymore.
Still up for debate.

Change flag icon style

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Radar.Script.txt

Replaced radar playermarker icon

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/Common/ClubTagUtils.Script.txt

ClubTagUtils: Replaced custom regex with TL::StripFormatting; Fixed color extraction

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Header.Script.txt

Closes #162 
More than an hour left: `Hh:Mm:Ss`
More than 10 seconds left: `Mm:Ss`
Less than 10 seconds left: `Mm:Ss.Cc`

Changed timer to TL functions for formatting

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Markers.Script.txt

fix: Hide flag height indicator if no GUIPlayer

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/FlagRush_ColorPalette.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Header.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/MVP.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Markers.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Radar.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Spectator.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/UIShared.Script.txt

Spectatorbutton refactor

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/Common/Commands/CommandUtils.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/Common/Commands/ModeCommands.Script.txt
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

Added new mode commands for matchcontrol and team balance

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/FlagRush_Logo.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/ScoresTable.Script.txt

Fixes as well the user avatar aspect ratios as seen here

Click a player on the scorestable to spectate them

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/Common/Commands/ModeCommands.Script.txt
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

Tiny change but very important :)

Add admins in ModeCommands

---

DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

This is the associated PR for #175. Feel free to discuss there if the message should be changed.

Change round start message

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/Header.Script.txt

184 Display overtime duration passed in header timer

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_UI.Script.txt

Added animations with only one line of code :)

Simple animations of scores table

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_UI.Script.txt

Until a better solution is found...

Revert scores table animations

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_UI.Script.txt
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

Up for debate if we want it or not. I think it's quite nice. :)
https://user-images.githubusercontent.com/53338174/181757254-e10c6550-d6a0-4806-b58a-399c61d97d9d.mp4

Enable spawn camera zoom animation

---

DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

Fix players respawning with flag on frameperfect respawn or death

---

DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

fix XmlRpc Callback order on flag scored.

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_FlagState.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_RpcEvents.Script.txt
DedicatedServer/Scripts/Modes/Trackmania/FlagRush.Script.txt

Fixes a bug where multiple players would try to pick up the flag in the same yield, leaving all the players that don't end up with the flag permanently handicapped (until they pickup and drop the flag again or respawn):
https://clips.twitch.tv/SparklyFastPanBCWarrior-kDsaOrjkNsnrb-Sv

Fix multiple players trying to pick up flag in same yield (fragile bug)

---

CHANGELOG.md
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/BaseModes/FlagRushProgressionBase.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/PodiumBackground.Script.txt

fix podium arrangement and skip sequence no podium on map

---

CHANGELOG.md
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/FlagMarker.Script.txt
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/FlagPossessionIndicator.Script.txt
DedicatedServer/Scripts/Modes/TrackMania/FlagRush.Script.txt

Adds a team-colored gradient to the top and bottom of the screen if player is carrying the flag (or spectator is watching the flag carrier)

Flag possession indicator

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/FlagMarker.Script.txt

Hide flag shadow by default

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/UI/Modules/FlagMarker.Script.txt

```
Error:
FlagRush_FlagMarker ()::Lerp01() [101, 50]
FlagRush_FlagMarker ()::Lerp01() [106, 67]
FlagRush_FlagMarker ()::UpdateLock() [202, 120]
FlagRush_FlagMarker ()::Main() [232, 15]
```
Closes #284

Fix div by zero in FlagMarker

---

DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/Flag.Script.txt

Send flag net updates when on player

---

CHANGELOG.md
DedicatedServer/Scripts/Libs/Zrx/ModeLibs/FlagRush/FlagRush_Vehicle.Script.txt
DedicatedServer/Scripts/Modes/TrackMania/FlagRush.Script.txt
Mode settings.md

Adds vehicle specific tunings (acceleration, adherence, control) to balance cars.
Closes #289

WIP: Add vehicle specific tunings

---

CHANGELOG.md
DedicatedServer/Scripts/Modes/TrackMania/FlagRush.Script.txt
Mode settings.md

Add light trails for the flag carrier
